apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim2
  labels:
    app: app1-development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
